const quizzes: Quiz[] = [
  {
    id: 1,
    title: 'ถ้าตลอดชีวิตของคุณสามารถเลือกดื่มน้ำได้ชนิดเดียว คุณจะดื่ม....',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'กาแฟ' },
      { id: Color.PINK, text: 'ชานม' },
      { id: Color.RED, text: 'แอลกอฮอล์' },
      { id: Color.GREEN, text: 'น้ำผลไม้' },
      { id: Color.YELLOW, text: 'อิตาเลียนโซดา' },
      { id: Color.ORANGE, text: 'น้ำอัดลม' },
      { id: Color.BLUE, text: 'น้ำวิตามิน' },
      { id: Color.PURPLE, text: 'เครื่องดื่มสมุนไพร' },
    ],
  },
  {
    id: 2,
    title: 'คุณจะแต่งตัวแบบไหนมา Colorists Festival',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'Minimal สะอาด เรียบร้อย' },
      { id: Color.PINK, text: 'น่ารักสดใส Colorful' },
      { id: Color.RED, text: 'เซ็กซี่ มั่นใจ ไม่กลัว' },
      { id: Color.GREEN, text: 'สบายๆ ชิวๆ' },
      { id: Color.YELLOW, text: 'Costplay จัดเต็ม' },
      { id: Color.ORANGE, text: 'นัดเพื่อนแต่งเป็นแก๊ง' },
      { id: Color.BLUE, text: 'สีเด่นๆนักร้องต้องเห็น' },
      { id: Color.PURPLE, text: 'หยิบอะไรได้ก็ใส่' },
    ],
  },
  {
    id: 3,
    title: 'ถ้าคุณจะไปเที่ยวกับเพื่อนคุณจะเลือกเดินทางด้วย....',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'รถSUV ขนสัมภาระได้เยอะ', image: PPV },
      { id: Color.PINK, text: 'รถเก๋ง เน้นความคล่องตัว', image: Sedan },
      { id: Color.RED, text: 'รถSuper car เร็วเแรงซิ่ง', image: Supercar },
      { id: Color.GREEN, text: 'รถไฟ ได้ชมบรรยากาศตลอดทาง', image: Train },
      { id: Color.YELLOW, text: 'รถตู้ เหมาได้ ไปด้วยกัน', image: Van },
      { id: Color.ORANGE, text: 'รถกระบะ ลุยได้ทุกสถานการณ์', image: Pickup },
      { id: Color.BLUE, text: 'มอเตอร์ไซค์ Road trip ขี่รถ ชมวิว', image: Motorcycle },
      { id: Color.PURPLE, text: 'รถทัวร์ ประหยัด นั่งสบาย', image: Bus },
    ],
  },
  {
    id: 4,
    title: 'เมื่อคุณเศร้าคุณจะ....',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'อ่านหนังสือ' },
      { id: Color.PINK, text: 'Shopping' },
      { id: Color.RED, text: 'ออกกำลังกาย/เล่นกีฬา' },
      { id: Color.GREEN, text: 'ปลูกต้นไม้' },
      { id: Color.YELLOW, text: 'เล่นเกม' },
      { id: Color.ORANGE, text: 'ทำอาหาร' },
      { id: Color.BLUE, text: 'วาดรูป' },
      { id: Color.PURPLE, text: 'ฟังเพลง' },
    ],
  },
  {
    id: 5,
    title: 'คุณเป็นขาประจำโซนไหนในคอนเสิร์ต',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'โซนสิงห์อมควัน ชิวๆเอาต์ดอร์' },
      { id: Color.PINK, text: 'โซนกิจกรรม ต้องร่วมให้ครบ' },
      { id: Color.RED, text: 'กลางๆ คนเยอะๆมันส์ๆ' },
      { id: Color.GREEN, text: 'เพื่อนอยู่ไหน เราอยู่นั่น' },
      { id: Color.YELLOW, text: 'หน้าเวที ใกล้ชิดศิลปิน' },
      { id: Color.ORANGE, text: 'โซนอาหาร ต้องใช้พลังงานเยอะ' },
      { id: Color.BLUE, text: 'ตรงไหนก็ได้โตแล้ว' },
      { id: Color.PURPLE, text: 'หลังสุดไม่ชอบเบียดใคร' },
    ],
  },
  {
    id: 6,
    title: 'ท้องฟ้าแบบไหนบ่งบอกอารมณ์คุณตอนนี้',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'ท้องฟ้ายามค่ำคืน' },
      { id: Color.PINK, text: 'Vanila SKy' },
      { id: Color.RED, text: 'ท้องฟ้าช่วงแดดจัด' },
      { id: Color.GREEN, text: 'ท้องฟ้าหลังฝนตกเห็นสายรุ้ง' },
      { id: Color.YELLOW, text: 'ช่วงพระอาทิตย์ขึ้น' },
      { id: Color.ORANGE, text: 'ช่วงพระอาทิตย์ตก' },
      { id: Color.BLUE, text: 'ท้องฟ้าโปร่งๆ' },
      { id: Color.PURPLE, text: 'ท้องฟ้าช่วงฝนตก' },
    ],
  },
  {
    id: 7,
    title: 'ถ้าคุณถูกล็อตเตอรี่รางวัลที่1คุณจะทำอะไร',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'นำไปลงทุนต่อยอด' },
      { id: Color.PINK, text: 'เปย์ตัวเองฉ่ำๆ' },
      { id: Color.RED, text: 'จ้างนักร้องในดวงใจมาแสดง' },
      { id: Color.GREEN, text: 'แบ่งไปทำบุญ' },
      { id: Color.YELLOW, text: 'ปิดซอยเลี้ยง' },
      { id: Color.ORANGE, text: 'แบ่งให้พ่อแม่ ซื้อบ้าน' },
      { id: Color.BLUE, text: 'ไปเที่ยวรอบโลก' },
      { id: Color.PURPLE, text: 'ใช้ให้หมดไม่สนลูกใคร' },
    ],
  },
  {
    id: 8,
    title: 'คุณเป็นสายไหนในคอนเสิร์ต',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'สายเก๊กขรึม คูลๆ' },
      { id: Color.PINK, text: 'สายโยกเบาๆ เพลินๆ' },
      { id: Color.RED, text: 'สายเต้นเท้าไฟ เต้นหมดไม่สนลูกใคร' },
      { id: Color.GREEN, text: 'สายนั่งฟัง ชิวๆ' },
      { id: Color.ORANGE, text: 'สายจริงจัง ซ้อมมาทุกเพลง' },
      { id: Color.BLUE, text: 'สายนิดนึง เดี๋ยวตามไป' },
      { id: Color.PURPLE, text: 'สายลึก เสพดนตรี' },
      { id: Color.YELLOW, text: 'สายกรี๊ดศิลปิน' },
    ],
  },
  {
    id: 9,
    title: 'สถานะความรักของคุณ',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'เรื่อยๆ รักกันม๊าก' },
      { id: Color.PINK, text: 'อินเลิฟสุดๆ โลกนี้เป็นสีชมพู' },
      { id: Color.RED, text: 'คุยไปก่อน ยังเลือกไม่ได้' },
      { id: Color.GREEN, text: 'แอบรักเพื่อน ก็มันหวั่นไหวนี่' },
      { id: Color.YELLOW, text: 'ยังไม่คิดเรื่องความรักเลยแกร' },
      { id: Color.ORANGE, text: 'ตามจีบเขาอยู่ ไม่รับรักสักที' },
      { id: Color.BLUE, text: 'อยู่คนเดียวสบายๆ' },
      { id: Color.PURPLE, text: 'อกหัก เศร้า เหงา แงๆ' },
    ],
  },
  {
    id: 10,
    title: 'คุณอยากหลุดเข้าไปใน Multiverse ไหน',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'โคนัน อยากไขคดี หาคนร้าย' },
      { id: Color.PINK, text: 'Barbie หวานๆใช้ชีวิตเกร๋ๆ' },
      { id: Color.RED, text: 'Marvel อยากร่วมทีมAvengers' },
      { id: Color.GREEN, text: 'เมาคลี อยากเป็นลูกหมาป่า' },
      { id: Color.YELLOW, text: 'ชินจัง อยากเป็นแก๊งเดียวกับชินจัง' },
      { id: Color.BLUE, text: 'Aladin นั่งพรมไปทุกที่' },
      { id: Color.PURPLE, text: 'Hogwart เสกคาถาโบกนิดสะบัดหน่อย' },
      { id: Color.ORANGE, text: 'Spongbob อยากใช้ชีวิตในเมืองใต้น้ำ' },
    ],
  },
  {
    id: 11,
    title: 'เมื่อคุณเข้างาน Colorists สิ่งแรกที่คุณจะทำคือ',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'สำรวจรอบงานว่ามีอะไรบ้าง' },
      { id: Color.PINK, text: 'ถ่ายรูปเช็คอินก่อนเลยหนึ่ง' },
      { id: Color.RED, text: 'เข้าบาร์เบียร์ก่อนเลย เมาปุ๊บสนุกปับ' },
      { id: Color.GREEN, text: 'เข้าบูธกิจกรรม ฉันต้องได้รางวัล' },
      { id: Color.YELLOW, text: 'รีบไปจองหน้าเวที ศิลปินต้องเห็นหน้าฉัน' },
      { id: Color.ORANGE, text: 'โซนอาหาร ฉันต้องอิ่มจะได้มีแรง' },
      { id: Color.BLUE, text: 'หาเพื่อนใหม่คอเดียวกัน' },
      { id: Color.PURPLE, text: 'หาที่นั่งรอคอนเสิร์ตเริ่ม' },
    ],
  },
  {
    id: 12,
    title: 'ชอบฟังเพลงแนวไหนที่สุด',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'สากล' },
      { id: Color.PINK, text: 'K-Pop' },
      { id: Color.RED, text: 'Hiphop' },
      { id: Color.GREEN, text: 'ลูกทุ่ง' },
      { id: Color.YELLOW, text: 'T-Pop' },
      { id: Color.ORANGE, text: 'Musical' },
      { id: Color.BLUE, text: 'ฟังเพลงแมสไปเรื่อยๆ' },
      { id: Color.PURPLE, text: 'Indy' },
    ],
  },
  {
    id: 13,
    title: 'คุณเป็นนักเที่ยวสายไหน',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'สายArt ที่ไหนมีgalleryต้องไป' },
      { id: Color.PINK, text: 'สายShopping ของมันต้องมี' },
      { id: Color.RED, text: 'สายเที่ยวกลางคืน ราตรีนี้ไม่เคยหลับใหล' },
      { id: Color.GREEN, text: 'สายธรรมชาติ หนีความวุ่นวาย' },
      { id: Color.YELLOW, text: 'สายกิน ร้านดีร้านอร่อยต้องเจอกัน' },
      { id: Color.ORANGE, text: 'สายไม่เคยอยู่บ้าน ไปเที่ยวตลอด' },
      { id: Color.BLUE, text: 'สายทำContent ที่ไหนเปิดใหม่ต้องไปเจิม' },
      { id: Color.PURPLE, text: 'สายบุญ การกระทำ30 ที่เหลือพึ่งดวง' },
    ],
  },
  {
    id: 14,
    title: 'ปกติคุณมักจะดู...',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'ภาพยนตร์ หนังเข้าแล้วเจอกัน' },
      { id: Color.PINK, text: 'ซีรีส์เกาหลี อปป้าซารางเฮ' },
      { id: Color.RED, text: 'ละครไทย พีเรียด ดราม่า' },
      { id: Color.GREEN, text: 'สารคดี ท่องโลก' },
      { id: Color.YELLOW, text: 'อนิเมะ ตอนใหม่มายัง' },
      { id: Color.ORANGE, text: 'คลิปสั้น Tiktok' },
      { id: Color.BLUE, text: 'ซีรีส์จีน กำลังภายใน' },
      { id: Color.PURPLE, text: 'รายการลี้ลับเล่าประสบการณ์ขนลุก' },
    ],
  },
  {
    id: 15,
    title: 'คุณเป็นใครในแก๊ง',
    choices: [
      { id: Color.LIGHT_BLUE, text: 'สายเงียบ ชอบฟังเพื่อนคุยกัน' },
      { id: Color.PINK, text: 'สายเทคแคร์ ซัพพอร์ตเพื่อน' },
      { id: Color.RED, text: 'สายเมาท์ เรื่องชาวบ้านเป็นเรื่องของเรา' },
      { id: Color.GREEN, text: 'สายที่ปรึกษา สุดท้ายก็หมาเหมือนเดิม' },
      { id: Color.YELLOW, text: 'สายกิน กินไปก่อนค่อยนับแคล' },
      { id: Color.ORANGE, text: 'สายตั้งตี้ ชวนไปเที่ยว' },
      { id: Color.BLUE, text: 'สายสาย ขอนอนก่อน' },
      { id: Color.PURPLE, text: 'สายเท ชวนกี่ทีก็เทตลอด' },
    ],
  },
]